// Code generated by Fastpb v0.0.2. DO NOT EDIT.

package core_api

import (
	fmt "fmt"
	fastpb "github.com/cloudwego/fastpb"
	basic "github.com/xh-polaris/ActiManage-IDL-gen/kitex_gen/basic"
)

var (
	_ = fmt.Errorf
	_ = fastpb.Skip
)
var _ = basic.File_basic_http_proto
