// Code generated by Kitex v0.12.1. DO NOT EDIT.

package coreapiservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	core_api "github.com/xh-polaris/ActiManage-IDL-gen/kitex_gen/core_api"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Login(ctx context.Context, Req *core_api.LoginReq, callOptions ...callopt.Option) (r *core_api.LoginResp, err error)
	SignUp(ctx context.Context, Req *core_api.SignUpReq, callOptions ...callopt.Option) (r *core_api.SignUpResp, err error)
	GetSetting(ctx context.Context, Req *core_api.GetSettingReq, callOptions ...callopt.Option) (r *core_api.GetSettingResp, err error)
	ListActivities(ctx context.Context, Req *core_api.ListActivitiesReq, callOptions ...callopt.Option) (r *core_api.ListActivitiesResp, err error)
	GetActivity(ctx context.Context, Req *core_api.GetActivityReq, callOptions ...callopt.Option) (r *core_api.GetActivityResp, err error)
	DoFavorite(ctx context.Context, Req *core_api.DoFavoriteReq, callOptions ...callopt.Option) (r *core_api.Response, err error)
	CancelFavorite(ctx context.Context, Req *core_api.CancelFavoriteReq, callOptions ...callopt.Option) (r *core_api.Response, err error)
	CreateBooking(ctx context.Context, Req *core_api.CreateBookingReq, callOptions ...callopt.Option) (r *core_api.Response, err error)
	CancelBookRecord(ctx context.Context, Req *core_api.CancelBookRecordReq, callOptions ...callopt.Option) (r *core_api.Response, err error)
	ListActivitiesByBookRecords(ctx context.Context, Req *core_api.ListBookRecordsReq, callOptions ...callopt.Option) (r *core_api.ListBookRecordsResp, err error)
	ListReservers(ctx context.Context, Req *core_api.ListReserversReq, callOptions ...callopt.Option) (r *core_api.ListReserversResp, err error)
	CreateReserver(ctx context.Context, Req *core_api.CreateReserverReq, callOptions ...callopt.Option) (r *core_api.Response, err error)
	DeleteReserver(ctx context.Context, Req *core_api.DeleteReserverReq, callOptions ...callopt.Option) (r *core_api.Response, err error)
	GetUserInfo(ctx context.Context, Req *core_api.GetUserInfoReq, callOptions ...callopt.Option) (r *core_api.GetUserInfoResp, err error)
	UpdateUserInfo(ctx context.Context, Req *core_api.UpdateUserInfoReq, callOptions ...callopt.Option) (r *core_api.Response, err error)
	UpdateNotice(ctx context.Context, Req *core_api.UpdateNoticeReq, callOptions ...callopt.Option) (r *core_api.Response, err error)
	MerchantListActivities(ctx context.Context, Req *core_api.MerchantListActivitiesReq, callOptions ...callopt.Option) (r *core_api.MerchantListActivitiesResp, err error)
	MerchantCreateActivity(ctx context.Context, Req *core_api.MerchantCreateActivityReq, callOptions ...callopt.Option) (r *core_api.Response, err error)
	MerchantDeleteActivity(ctx context.Context, Req *core_api.MerchantDeleteActivityReq, callOptions ...callopt.Option) (r *core_api.Response, err error)
	MerchantTopActivity(ctx context.Context, Req *core_api.MerchantTopActivityReq, callOptions ...callopt.Option) (r *core_api.Response, err error)
	MerchantLogin(ctx context.Context, Req *core_api.MerchantLoginReq, callOptions ...callopt.Option) (r *core_api.MerchantLoginResp, err error)
	MerchantGetSetting(ctx context.Context, Req *core_api.MerchantGetSettingReq, callOptions ...callopt.Option) (r *core_api.MerchantGetSettingResp, err error)
	MerchantUpdateSetting(ctx context.Context, Req *core_api.MerchantUpdateSettingReq, callOptions ...callopt.Option) (r *core_api.MerchantGetSettingResp, err error)
	MerchantGetBookRecords(ctx context.Context, Req *core_api.MerchantListBookRecordsReq, callOptions ...callopt.Option) (r *core_api.MerchantListBookRecordsResp, err error)
	MerchantUpdateInfo(ctx context.Context, Req *core_api.MerchantUpdateInfoReq, callOptions ...callopt.Option) (r *core_api.Response, err error)
	MerchantGetInfo(ctx context.Context, Req *core_api.MerchantGetInfoReq, callOptions ...callopt.Option) (r *core_api.MerchantGetInfoResp, err error)
	MerchantSetPassword(ctx context.Context, Req *core_api.MerchantSetPasswordReq, callOptions ...callopt.Option) (r *core_api.Response, err error)
	SystemLogin(ctx context.Context, Req *core_api.SystemLoginReq, callOptions ...callopt.Option) (r *core_api.SystemLoginResp, err error)
	SystemListMerchant(ctx context.Context, Req *core_api.SystemListMerchantsReq, callOptions ...callopt.Option) (r *core_api.SystemListMerchantsReq, err error)
	SystemGetMerchant(ctx context.Context, Req *core_api.SystemGetMerchantReq, callOptions ...callopt.Option) (r *core_api.SystemGetMerchantResp, err error)
	SystemCreateMerchant(ctx context.Context, Req *core_api.SystemCreateMerchantReq, callOptions ...callopt.Option) (r *core_api.Response, err error)
	SystemUpdateMerchant(ctx context.Context, Req *core_api.SystemUpdateMerchantReq, callOptions ...callopt.Option) (r *core_api.Response, err error)
	SystemGetDashboard(ctx context.Context, Req *core_api.SystemGetDashboardReq, callOptions ...callopt.Option) (r *core_api.SystemGetDashboardResp, err error)
	SystemGetOverallDashboard(ctx context.Context, Req *core_api.SystemGetOverallDashboardReq, callOptions ...callopt.Option) (r *core_api.SystemGetOverallDashboardResp, err error)
	StsApplySignedUrl(ctx context.Context, Req *core_api.StsApplySignedUrlReq, callOptions ...callopt.Option) (r *core_api.StsApplySignedUrlResp, err error)
	StsAIModify(ctx context.Context, Req *core_api.StsAIModifyReq, callOptions ...callopt.Option) (r *core_api.StsAIModifyResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kCoreApiServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kCoreApiServiceClient struct {
	*kClient
}

func (p *kCoreApiServiceClient) Login(ctx context.Context, Req *core_api.LoginReq, callOptions ...callopt.Option) (r *core_api.LoginResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Login(ctx, Req)
}

func (p *kCoreApiServiceClient) SignUp(ctx context.Context, Req *core_api.SignUpReq, callOptions ...callopt.Option) (r *core_api.SignUpResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SignUp(ctx, Req)
}

func (p *kCoreApiServiceClient) GetSetting(ctx context.Context, Req *core_api.GetSettingReq, callOptions ...callopt.Option) (r *core_api.GetSettingResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetSetting(ctx, Req)
}

func (p *kCoreApiServiceClient) ListActivities(ctx context.Context, Req *core_api.ListActivitiesReq, callOptions ...callopt.Option) (r *core_api.ListActivitiesResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListActivities(ctx, Req)
}

func (p *kCoreApiServiceClient) GetActivity(ctx context.Context, Req *core_api.GetActivityReq, callOptions ...callopt.Option) (r *core_api.GetActivityResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetActivity(ctx, Req)
}

func (p *kCoreApiServiceClient) DoFavorite(ctx context.Context, Req *core_api.DoFavoriteReq, callOptions ...callopt.Option) (r *core_api.Response, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DoFavorite(ctx, Req)
}

func (p *kCoreApiServiceClient) CancelFavorite(ctx context.Context, Req *core_api.CancelFavoriteReq, callOptions ...callopt.Option) (r *core_api.Response, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CancelFavorite(ctx, Req)
}

func (p *kCoreApiServiceClient) CreateBooking(ctx context.Context, Req *core_api.CreateBookingReq, callOptions ...callopt.Option) (r *core_api.Response, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateBooking(ctx, Req)
}

func (p *kCoreApiServiceClient) CancelBookRecord(ctx context.Context, Req *core_api.CancelBookRecordReq, callOptions ...callopt.Option) (r *core_api.Response, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CancelBookRecord(ctx, Req)
}

func (p *kCoreApiServiceClient) ListActivitiesByBookRecords(ctx context.Context, Req *core_api.ListBookRecordsReq, callOptions ...callopt.Option) (r *core_api.ListBookRecordsResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListActivitiesByBookRecords(ctx, Req)
}

func (p *kCoreApiServiceClient) ListReservers(ctx context.Context, Req *core_api.ListReserversReq, callOptions ...callopt.Option) (r *core_api.ListReserversResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListReservers(ctx, Req)
}

func (p *kCoreApiServiceClient) CreateReserver(ctx context.Context, Req *core_api.CreateReserverReq, callOptions ...callopt.Option) (r *core_api.Response, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateReserver(ctx, Req)
}

func (p *kCoreApiServiceClient) DeleteReserver(ctx context.Context, Req *core_api.DeleteReserverReq, callOptions ...callopt.Option) (r *core_api.Response, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteReserver(ctx, Req)
}

func (p *kCoreApiServiceClient) GetUserInfo(ctx context.Context, Req *core_api.GetUserInfoReq, callOptions ...callopt.Option) (r *core_api.GetUserInfoResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetUserInfo(ctx, Req)
}

func (p *kCoreApiServiceClient) UpdateUserInfo(ctx context.Context, Req *core_api.UpdateUserInfoReq, callOptions ...callopt.Option) (r *core_api.Response, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateUserInfo(ctx, Req)
}

func (p *kCoreApiServiceClient) UpdateNotice(ctx context.Context, Req *core_api.UpdateNoticeReq, callOptions ...callopt.Option) (r *core_api.Response, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateNotice(ctx, Req)
}

func (p *kCoreApiServiceClient) MerchantListActivities(ctx context.Context, Req *core_api.MerchantListActivitiesReq, callOptions ...callopt.Option) (r *core_api.MerchantListActivitiesResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.MerchantListActivities(ctx, Req)
}

func (p *kCoreApiServiceClient) MerchantCreateActivity(ctx context.Context, Req *core_api.MerchantCreateActivityReq, callOptions ...callopt.Option) (r *core_api.Response, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.MerchantCreateActivity(ctx, Req)
}

func (p *kCoreApiServiceClient) MerchantDeleteActivity(ctx context.Context, Req *core_api.MerchantDeleteActivityReq, callOptions ...callopt.Option) (r *core_api.Response, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.MerchantDeleteActivity(ctx, Req)
}

func (p *kCoreApiServiceClient) MerchantTopActivity(ctx context.Context, Req *core_api.MerchantTopActivityReq, callOptions ...callopt.Option) (r *core_api.Response, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.MerchantTopActivity(ctx, Req)
}

func (p *kCoreApiServiceClient) MerchantLogin(ctx context.Context, Req *core_api.MerchantLoginReq, callOptions ...callopt.Option) (r *core_api.MerchantLoginResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.MerchantLogin(ctx, Req)
}

func (p *kCoreApiServiceClient) MerchantGetSetting(ctx context.Context, Req *core_api.MerchantGetSettingReq, callOptions ...callopt.Option) (r *core_api.MerchantGetSettingResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.MerchantGetSetting(ctx, Req)
}

func (p *kCoreApiServiceClient) MerchantUpdateSetting(ctx context.Context, Req *core_api.MerchantUpdateSettingReq, callOptions ...callopt.Option) (r *core_api.MerchantGetSettingResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.MerchantUpdateSetting(ctx, Req)
}

func (p *kCoreApiServiceClient) MerchantGetBookRecords(ctx context.Context, Req *core_api.MerchantListBookRecordsReq, callOptions ...callopt.Option) (r *core_api.MerchantListBookRecordsResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.MerchantGetBookRecords(ctx, Req)
}

func (p *kCoreApiServiceClient) MerchantUpdateInfo(ctx context.Context, Req *core_api.MerchantUpdateInfoReq, callOptions ...callopt.Option) (r *core_api.Response, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.MerchantUpdateInfo(ctx, Req)
}

func (p *kCoreApiServiceClient) MerchantGetInfo(ctx context.Context, Req *core_api.MerchantGetInfoReq, callOptions ...callopt.Option) (r *core_api.MerchantGetInfoResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.MerchantGetInfo(ctx, Req)
}

func (p *kCoreApiServiceClient) MerchantSetPassword(ctx context.Context, Req *core_api.MerchantSetPasswordReq, callOptions ...callopt.Option) (r *core_api.Response, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.MerchantSetPassword(ctx, Req)
}

func (p *kCoreApiServiceClient) SystemLogin(ctx context.Context, Req *core_api.SystemLoginReq, callOptions ...callopt.Option) (r *core_api.SystemLoginResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SystemLogin(ctx, Req)
}

func (p *kCoreApiServiceClient) SystemListMerchant(ctx context.Context, Req *core_api.SystemListMerchantsReq, callOptions ...callopt.Option) (r *core_api.SystemListMerchantsReq, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SystemListMerchant(ctx, Req)
}

func (p *kCoreApiServiceClient) SystemGetMerchant(ctx context.Context, Req *core_api.SystemGetMerchantReq, callOptions ...callopt.Option) (r *core_api.SystemGetMerchantResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SystemGetMerchant(ctx, Req)
}

func (p *kCoreApiServiceClient) SystemCreateMerchant(ctx context.Context, Req *core_api.SystemCreateMerchantReq, callOptions ...callopt.Option) (r *core_api.Response, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SystemCreateMerchant(ctx, Req)
}

func (p *kCoreApiServiceClient) SystemUpdateMerchant(ctx context.Context, Req *core_api.SystemUpdateMerchantReq, callOptions ...callopt.Option) (r *core_api.Response, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SystemUpdateMerchant(ctx, Req)
}

func (p *kCoreApiServiceClient) SystemGetDashboard(ctx context.Context, Req *core_api.SystemGetDashboardReq, callOptions ...callopt.Option) (r *core_api.SystemGetDashboardResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SystemGetDashboard(ctx, Req)
}

func (p *kCoreApiServiceClient) SystemGetOverallDashboard(ctx context.Context, Req *core_api.SystemGetOverallDashboardReq, callOptions ...callopt.Option) (r *core_api.SystemGetOverallDashboardResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SystemGetOverallDashboard(ctx, Req)
}

func (p *kCoreApiServiceClient) StsApplySignedUrl(ctx context.Context, Req *core_api.StsApplySignedUrlReq, callOptions ...callopt.Option) (r *core_api.StsApplySignedUrlResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.StsApplySignedUrl(ctx, Req)
}

func (p *kCoreApiServiceClient) StsAIModify(ctx context.Context, Req *core_api.StsAIModifyReq, callOptions ...callopt.Option) (r *core_api.StsAIModifyResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.StsAIModify(ctx, Req)
}
