// Code generated by Kitex v0.12.1. DO NOT EDIT.
package coreapiservice

import (
	server "github.com/cloudwego/kitex/server"
	userr "github.com/xh-polaris/ActiManage-IDL-gen/kitex_gen/userr"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler userr.CoreApiService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}

func RegisterService(svr server.Server, handler userr.CoreApiService, opts ...server.RegisterOption) error {
	return svr.RegisterService(serviceInfo(), handler, opts...)
}
