// Code generated by Fastpb v0.0.2. DO NOT EDIT.

package basic

import (
	fmt "fmt"
	fastpb "github.com/cloudwego/fastpb"
)

var (
	_ = fmt.Errorf
	_ = fastpb.Skip
)

func (x *Paging) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	case 2:
		offset, err = x.fastReadField2(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_Paging[number], err)
}

func (x *Paging) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	tmp, offset, err := fastpb.ReadInt64(buf, _type)
	x.Page = &tmp
	return offset, err
}

func (x *Paging) fastReadField2(buf []byte, _type int8) (offset int, err error) {
	tmp, offset, err := fastpb.ReadInt64(buf, _type)
	x.Limit = &tmp
	return offset, err
}

func (x *Paging) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	offset += x.fastWriteField2(buf[offset:])
	return offset
}

func (x *Paging) fastWriteField1(buf []byte) (offset int) {
	if x.Page == nil {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 1, x.GetPage())
	return offset
}

func (x *Paging) fastWriteField2(buf []byte) (offset int) {
	if x.Limit == nil {
		return offset
	}
	offset += fastpb.WriteInt64(buf[offset:], 2, x.GetLimit())
	return offset
}

func (x *Paging) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	n += x.sizeField2()
	return n
}

func (x *Paging) sizeField1() (n int) {
	if x.Page == nil {
		return n
	}
	n += fastpb.SizeInt64(1, x.GetPage())
	return n
}

func (x *Paging) sizeField2() (n int) {
	if x.Limit == nil {
		return n
	}
	n += fastpb.SizeInt64(2, x.GetLimit())
	return n
}

var fieldIDToName_Paging = map[int32]string{
	1: "Page",
	2: "Limit",
}
