// Code generated by Kitex v0.12.3. DO NOT EDIT.

package sts

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	core_api "github.com/xh-polaris/ActiManage-IDL-gen/kitex_gen/core_api"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	StsApplySignedUrl(ctx context.Context, Req *core_api.StsApplySignedUrlReq, callOptions ...callopt.Option) (r *core_api.StsApplySignedUrlResp, err error)
	StsAIModify(ctx context.Context, Req *core_api.StsAIModifyReq, callOptions ...callopt.Option) (r *core_api.StsAIModifyResp, err error)
	StsSendVerifyCode(ctx context.Context, Req *core_api.StsSendVerifyCodeReq, callOptions ...callopt.Option) (r *core_api.Response, err error)
	StsView(ctx context.Context, Req *core_api.StsViewReq, callOptions ...callopt.Option) (r *core_api.Response, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kStsClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kStsClient struct {
	*kClient
}

func (p *kStsClient) StsApplySignedUrl(ctx context.Context, Req *core_api.StsApplySignedUrlReq, callOptions ...callopt.Option) (r *core_api.StsApplySignedUrlResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.StsApplySignedUrl(ctx, Req)
}

func (p *kStsClient) StsAIModify(ctx context.Context, Req *core_api.StsAIModifyReq, callOptions ...callopt.Option) (r *core_api.StsAIModifyResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.StsAIModify(ctx, Req)
}

func (p *kStsClient) StsSendVerifyCode(ctx context.Context, Req *core_api.StsSendVerifyCodeReq, callOptions ...callopt.Option) (r *core_api.Response, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.StsSendVerifyCode(ctx, Req)
}

func (p *kStsClient) StsView(ctx context.Context, Req *core_api.StsViewReq, callOptions ...callopt.Option) (r *core_api.Response, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.StsView(ctx, Req)
}
